# Generated by Django 4.1 on 2022-09-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item_title',
            field=models.CharField(max_length=100),
        ),
    ]
