# Generated by Django 4.1 on 2022-09-28 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_task_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='item_title',
            new_name='title',
        ),
    ]
