# Generated by Django 4.1 on 2022-09-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_task_item_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='item_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='item_user',
            new_name='usernames',
        ),
    ]
