# Generated by Django 4.1 on 2022-09-21 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_watchistitem_delete_watchlistitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchistItem',
            new_name='watchlistItem',
        ),
    ]
